MetanitExampleCoreMVC/MetanitExampleCoreMVC/ViewModels/FilterSortPagingViewModel.cs
using MetanitExampleCoreMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MetanitExampleCoreMVC.ViewModels
{
    public class FilterSortPagingViewModel
    {
        public IEnumerable<User> Users { get; set; }
        public PageViewModel PageViewModel { get; set; }
        public FilterViewModel FilterViewModel { get; set; }
        public SortSecondViewModel SortViewModel { get; set; }
    }
}

MetanitExampleCoreMVC/MetanitExampleCoreMVC/ViewModels/FilterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MetanitExampleCoreMVC.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MetanitExampleCoreMVC.ViewModels
{
    public class FilterViewModel
    {
        public FilterViewModel(List<Company> companies, int? company, string name)
        {
            // устанавливаем начальный элемент, который позволит выбрать всех
            companies.Insert(0, new Company { Name = "Все", Id = 0 });
            Companies = new SelectList(companies, "Id", "Name", company);
            SelectedCompany = company;
            SelectedName = name;
        }
        public SelectList Companies { get; private set; } // список компаний
        public int? SelectedCompany { get; private set; }   // выбранная компания
        public string SelectedName { get; private set; }    // введенное имя
    }
}

MetanitExampleCoreMVC/MetanitExampleCoreMVC/ViewModels/SortViewModel.cs
using MetanitExampleCoreMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MetanitExampleCoreMVC.ViewModels
{
    public class SortViewModel
    {
        public SortState NameSort { get; set; }
        public SortState AgeSort { get; set; }
        public SortState CompanySort { get; set; }
        public SortState Current { get; set; }
        public bool Up { get; set; }

        public SortViewModel(SortState sortOrder)
        {
            NameSort = SortState.NameAsc;
            AgeSort = SortState.AgeAsc;
            CompanySort = SortState.CompanyAsc;
            Up = true;

            if (sortOrder == SortState.AgeDesc || sortOrder == SortState.NameDesc
                || sortOrder == SortState.CompanyDesc)
            {
                Up = false;
            }

            switch (sortOrder)
            {
                case SortState.NameDesc:
                    Current = NameSort = SortState.NameAsc;
                    break;
                case SortState.AgeAsc:
                    Current = AgeSort = SortState.AgeDesc;
                    break;
                case SortState.AgeDesc:
                    Current = AgeSort = SortState.AgeAsc;
                    break;
                case SortState.CompanyAsc:
                    Current = CompanySort = SortState.CompanyDesc;
                    break;
                case SortState.CompanyDesc:
                    Current = CompanySort = SortState.CompanyAsc;
                    break;
                default:
                    Current = NameSort = SortState.NameDesc;
                    break;
            }
        }
    }
}

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Controllers/DataModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MetanitExampleCoreMVC.Models;
using MetanitExampleCoreMVC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query;

namespace MetanitExampleCoreMVC.Controllers
{
    public class DataModelController : Controller
    {
        private MobileContext db;
        private UsersContext dbUsers;

        public DataModelController(MobileContext context, UsersContext usersContext)
        {
            db = context;
            dbUsers = usersContext;
        }

        public async Task<IActionResult> Index()
        {
            return View(await db.Phones.ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Phone phone)
        {
            db.Phones.Add(phone);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                Phone phone = await db.Phones.FirstOrDefaultAsync(p => p.Id == id);

                if (phone != null)
                {
                    return View(phone);
                }
            }

            return NotFound();
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Phone phone = await db.Phones.FirstOrDefaultAsync(p => p.Id == id);

                if (phone != null)
                {
                    return View(phone);
                }
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Phone phone)
        {
            db.Phones.Update(phone);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id != null)
            {
                Phone phone = await db.Phones.FirstOrDefaultAsync(p => p.Id == id);

                if (phone != null)
                {
                    return View(phone);
                }
            }

            return NotFound();
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {

                //Phone phone = new Phone { Id = id.Value };
                //db.Entry(phone).State = EntityState.Deleted;
                //await db.SaveChangesAsync();
                //return RedirectToAction("Index");

                Phone phone = await db.Phones.FirstOrDefaultAsync(p => p.Id == id);

                if (phone != null)
                {
                    db.Phones.Remove(phone);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }

            return NotFound();
        }

        public async Task<IActionResult> Sort(SortState sortOrder = SortState.NameAsc)
        {
            IIncludableQueryable<MetanitExampleCoreMVC.Models.User, Company> users = dbUsers.Users.Include(x => x.Company);
            IQueryable<MetanitExampleCoreMVC.Models.User> usersResult;

            ViewData["NameSort"] = sortOrder == SortState.NameAsc ? SortState.NameDesc : SortState.NameAsc;
            ViewData["AgeSort"] = sortOrder == SortState.AgeAsc ? SortState.AgeDesc : SortState.AgeAsc;
            ViewData["CompanySort"] = sortOrder == SortState.CompanyAsc ? SortState.CompanyDesc : SortState.CompanyAsc;

            switch (sortOrder)
            {
                case SortState.NameDesc:
                    usersResult = users.OrderByDescending(s => s.Name);
                    break;
                case SortState.AgeAsc:
                    usersResult = users.OrderBy(s => s.Name);
                    break;
                case SortState.AgeDesc:
                    usersResult = users.OrderByDescending(s => s.Name);
                    break;
                case SortState.CompanyAsc:
                    usersResult = users.OrderBy(s => s.Name);
                    break;
                case SortState.CompanyDesc:
                    usersResult = users.OrderByDescending(s => s.Company.Name);
                    break;
                default:
                    usersResult = users.OrderBy(s => s.Name);
                    break;
            }

            IndexSortViewModel viewModel = new IndexSortViewModel
            {
                Users = await usersResult.AsNoTracking().ToListAsync(),
                SortViewModel = new SortViewModel(sortOrder)
            };

            return View(viewModel);
        }

        public IActionResult Filter(int? company, string name)
        {
            IIncludableQueryable<MetanitExampleCoreMVC.Models.User, Company> users = dbUsers.Users.Include(p => p.Company);
            IQueryable<MetanitExampleCoreMVC.Models.User> usersResult = null;
            if (company != null && company != 0)
            {
                usersResult = users.Where(p => p.CompanyId == company);
            }
            else
            {
                usersResult = users;
            }

            if (!String.IsNullOrEmpty(name))
            {
                usersResult = usersResult.Where(p => p.Name.Contains(name));
            }

            List<Company> companies = dbUsers.Companies.ToList();
            // устанавливаем начальный элемент, который позволит выбрать всех
            companies.Insert(0, new Company { Name = "Все", Id = 0 });

            UsersListViewModel viewModel = new UsersListViewModel
            {
                Users = usersResult?.ToList(),
                Companies = new SelectList(companies, "Id", "Name"),
                Name = name
            };

            return View(viewModel);
        }

        public async Task<IActionResult> Pagination(int page = 1)
        {
            int pageSize = 1;
            IIncludableQueryable<MetanitExampleCoreMVC.Models.User, Company> source = dbUsers.Users.Include(x => x.Company);
            var count = await source.CountAsync();
            var items = await source.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();
            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexPageViewModel viewModel = new IndexPageViewModel()
            {
                PageViewModel = pageViewModel,
                Users = items
            };

            return View(viewModel);
        }

        public async Task<IActionResult> FilterSortPaging(int? company, string name, int page = 1,
           SortState sortOrder = SortState.NameAsc)
        {
            int pageSize = 1;

            //фильтрация
            IQueryable<MetanitExampleCoreMVC.Models.User> users = dbUsers.Users.Include(x => x.Company);

            if (company != null && company != 0)
            {
                users = users.Where(p => p.CompanyId == company);
            }
            if (!String.IsNullOrEmpty(name))
            {
                users = users.Where(p => p.Name.Contains(name));
            }

            // сортировка
            switch (sortOrder)
            {
                case SortState.NameDesc:
                    users = users.OrderByDescending(s => s.Name);
                    break;
                case SortState.AgeAsc:
                    users = users.OrderBy(s => s.Age);
                    break;
                case SortState.AgeDesc:
                    users = users.OrderByDescending(s => s.Age);
                    break;
                case SortState.CompanyAsc:
                    users = users.OrderBy(s => s.Company.Name);
                    break;
                case SortState.CompanyDesc:
                    users = users.OrderByDescending(s => s.Company.Name);
                    break;
                default:
                    users = users.OrderBy(s => s.Name);
                    break;
            }

            // пагинация
            var count = await users.CountAsync();
            var items = await users.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();

            // формируем модель представления
            FilterSortPagingViewModel viewModel = new FilterSortPagingViewModel
            {
                PageViewModel = new PageViewModel(count, page, pageSize),
                SortViewModel = new SortSecondViewModel(sortOrder),
                FilterViewModel = new FilterViewModel(dbUsers.Companies.ToList(), company, name),
                Users = items
            };

            return View(viewModel);
        }
    }
}

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Controllers/FiltersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MetanitExampleCoreMVC.Filters;
using Microsoft.AspNetCore.Mvc;

namespace MetanitExampleCoreMVC.Controllers
{
    //[SimpleActionFilter]
    [RequireHttps]
    public class FiltersController : Controller
    {
        //[SimpleActionFilter]
        //[SimpleResourceFilter(30, "Hello")]
        //[ServiceFilter(typeof(SimpleResourceFilter))]
        //[TypeFilter(typeof(SimpleResourceFilter))]
        //[IEFilter]
        //[Whitespace]
        [TimeExecutionFilter]
        public IActionResult Index()
        {
            return View();
        }
    }
}

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Views/DataModel/Create.cshtml
@model MetanitExampleCoreMVC.Models.Phone
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="create" asp-controller="DataModel">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Название</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Company" class="control-label">Компания</label>
        <input type="text" asp-for="Company" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Price" class="control-label">Цена</label>
        <input type="number" asp-for="Price" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Send" class="btn btn-default" />
    </div>
</form>

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Views/DataModel/Delete.cshtml
@model MetanitExampleCoreMVC.Models.Phone
@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<div>
    <dl class="dl-horizontal">
        <dt>Название</dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>Производитель</dt>
        <dd>
            @Html.DisplayFor(model => model.Company)
        </dd>

        <dt>Цена</dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>

    <div>
        <form asp-controller="DataModel" asp-action="Delete" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Удалить" />
            </div>
        </form>
    </div>
</div>

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Views/DataModel/Details.cshtml
@model MetanitExampleCoreMVC.Models.Phone
@{
    ViewData["Title"] = Model.Name;
}

<h2>Details about @Model.Name</h2>
<div>
    <dl class="dl-horizontal">
        <dt>Производитель</dt>
        <dd>@Model.Company</dd>

        <dt>Цена</dt>
        <dd>@Model.Price</dd>
    </dl>
</div>

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Views/DataModel/Edit.cshtml
@model MetanitExampleCoreMVC.Models.Phone
@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="edit" asp-controller="DataModel" asp-route-id="@Model.Id">
    <div class="form-group">
        <label asp-for="Name" class="control-label">Название</label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Company" class="control-label">Компания</label>
        <input type="text" asp-for="Company" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Price" class="control-label">Цена</label>
        <input type="number" asp-for="Price" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Send" class="btn btn-default" />
    </div>
</form>

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Views/DataModel/Filter.cshtml
@model UsersListViewModel
@{
    ViewData["Title"] = "Filter";
}

<h2>Filter</h2>

<form method="get">
    <div class="form-inline form-group">
        <label class="control-label">Имя: </label>
        @Html.TextBox("name", Model.Name, htmlAttributes: new { @class = "form-control" })

        <label class="control-label">Компания: </label>
        @Html.DropDownList("company", Model.Companies as SelectList,
                              htmlAttributes: new { @class = "form-control" })

        <input type="submit" value="Фильтр" class="btn btn-default" />
    </div>
</form>

<table class="table table-striped">
    <tr>
        <th>Имя</th>
        <th>Возраст</th>
        <th>Компания</th>
    </tr>

    @foreach (var item in Model.Users)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Company.Name)
            </td>
        </tr>
    }
</table>

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Views/DataModel/FilterSortPaging.cshtml
@model FilterSortPagingViewModel
@{
    ViewData["Title"] = "FilterSortPaging";
}

<h2>FilterSortPaging</h2>

<h1>Список пользователей</h1>
<form method="get">
    <div class="form-inline">
        <label class="control-label">Имя: </label>
        @Html.TextBox("name", Model.FilterViewModel.SelectedName, htmlAttributes: new { @class = "form-control" })

        <label class="control-label">Компания: </label>
        @Html.DropDownList("company", Model.FilterViewModel.Companies as SelectList,
                                         htmlAttributes: new { @class = "form-control" })

        <input type="submit" value="Фильтр" class="btn btn-default" />
    </div>
</form>

<table class="table">
    <tr>
        <th>
            <a asp-action="FilterSortPaging"
               asp-route-sortOrder="@(Model.SortViewModel.NameSort)"
               asp-route-name="@(Model.FilterViewModel.SelectedName)"
               asp-route-company="@(Model.FilterViewModel.SelectedCompany)">Имя</a>
        </th>
        <th>
            <a asp-action="FilterSortPaging" asp-route-sortOrder="@(Model.SortViewModel.AgeSort)"
               asp-route-name="@(Model.FilterViewModel.SelectedName)"
               asp-route-company="@(Model.FilterViewModel.SelectedCompany)">Возраст</a>
        </th>
        <th>
            <a asp-action="FilterSortPaging" asp-route-sortOrder="@(Model.SortViewModel.CompanySort)"
               asp-route-name="@(Model.FilterViewModel.SelectedName)"
               asp-route-company="@(Model.FilterViewModel.SelectedCompany)">Компания</a>
        </th>
    </tr>
    @foreach (var u in Model.Users)
    {
        <tr><td>@u.Name</td><td>@u.Age</td><td>@u.Company.Name</td></tr>
    }
</table>
@*@if (Model.PageViewModel.HasPreviousPage)
    {
        <a asp-action="FilterSortPaging"
           asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
           asp-route-name="@(Model.FilterViewModel.SelectedName)"
           asp-route-company="@(Model.FilterViewModel.SelectedCompany)"
           asp-route-sortorder="@(Model.SortViewModel.Current)"
           class="btn btn-default btn">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Назад
        </a>
    }
    @if (Model.PageViewModel.HasNextPage)
    {
        <a asp-action="FilterSortPaging"
           asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
           asp-route-name="@(Model.FilterViewModel.SelectedName)"
           asp-route-company="@(Model.FilterViewModel.SelectedCompany)"
           asp-route-sortorder="@(Model.SortViewModel.Current)"
           class="btn btn-default btn">
            Вперед
            <i class="glyphicon glyphicon-chevron-right"></i>
        </a>
    }*@
<page-link-filter-sort-paging page-model="Model.PageViewModel" page-action="FilterSortPaging"
           page-url-name="@(Model.FilterViewModel.SelectedName)"
           page-url-company="@(Model.FilterViewModel.SelectedCompany)"
           page-url-sortorder="@(Model.SortViewModel.Current)"></page-link-filter-sort-paging>

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Views/DataModel/Index.cshtml
@model IEnumerable<MetanitExampleCoreMVC.Models.Phone>
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<a asp-action="Create">Добавить модель</a>
<table class="table">
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>
                <a asp-action="Details" asp-controller="DataModel" asp-route-id="@item.Id">Подробнее</a> |
                <a asp-action="Edit" asp-controller="DataModel" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Delete" asp-controller="DataModel" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
    }
</table>

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Views/DataModel/Pagination.cshtml
@model IndexPageViewModel
@{
    ViewData["Title"] = "Pagination";
}

<h2>Pagination</h2>

<table class="table">
    <tr><th>Имя</th><th>Возраст</th><th>Компания</th></tr>
    @foreach (var u in Model.Users)
    {
        <tr><td>@u.Name</td><td>@u.Age</td><td>@u.Company.Name</td></tr>
    }
</table>
<page-link page-model="Model.PageViewModel" page-action="Pagination"></page-link>
@*@if (Model.PageViewModel.HasPreviousPage)
{
    <a asp-action="Pagination"
       asp-route-page="@(Model.PageViewModel.PageNumber - 1)"
       class="btn btn-default btn">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Назад
    </a>
}
@if (Model.PageViewModel.HasNextPage)
{
    <a asp-action="Pagination"
       asp-route-page="@(Model.PageViewModel.PageNumber + 1)"
       class="btn btn-default btn">
        <i class="glyphicon glyphicon-chevron-right"></i>
        Вперед
    </a>
}*@

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Views/DataModel/Sort.cshtml
@*@model IEnumerable<MetanitExampleCoreMVC.Models.User>*@
@model IndexSortViewModel
@{
    ViewData["Title"] = "Sort";
}

<h2>Sort</h2>

<h1>Список пользователей</h1>
<table class="table">
    <tr>
        <th>
            <sort-header action="Sort" up="@Model.SortViewModel.Up"
                         current="@Model.SortViewModel.Current" property="@Model.SortViewModel.NameSort">
                Имя
            </sort-header>
        </th>
        <th>
            <sort-header action="Sort" up="@Model.SortViewModel.Up"
                         current="@Model.SortViewModel.Current" property="@Model.SortViewModel.AgeSort">
                Возраст
            </sort-header>
        </th>
        <th>
            <sort-header action="Sort" up="@Model.SortViewModel.Up"
                         current="@Model.SortViewModel.Current" property="@Model.SortViewModel.CompanySort">
                Компания
            </sort-header>
        </th>
    </tr>
    @foreach (MetanitExampleCoreMVC.Models.User u in Model.Users)
    {
        <tr><td>@u.Name</td><td>@u.Age</td><td>@u.Company.Name</td></tr>
    }
</table>