MetanitExampleCoreMVC/MetanitExampleCoreMVC/Controllers/HtmlHelpersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MetanitExampleCoreMVC.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace MetanitExampleCoreMVC.Controllers
{
    public enum TimeOfDay
    {
        [Display(Name = "Утро")]
        Morning,
        [Display(Name = "День")]
        Afternoon,
        [Display(Name = "Вечер")]
        Evening,
        [Display(Name = "Ночь")]
        Night
    }

    public class HtmlHelpersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            List<Phone> phones = new List<Phone>
            {
                new Phone {Id=1, Name="iPhone 7 Pro", Price=680 },
                new Phone {Id=2, Name="Galaxy 7 Edge", Price=640 },
                new Phone {Id=3, Name="HTC 10", Price=500 },
                new Phone {Id=4, Name="Honor 5X", Price=400 },
            };
            ViewBag.Phones = new SelectList(phones, "Id", "Name");

            return View();
        }

        [HttpPost]
        public IActionResult Create(Phone3 phone)
        {
            return Content(phone.Name);
        }

        public IActionResult Display()
        {
            Phone phone = new Phone() { Id = 1, Name = "Nexus 6P", Price = 49000 };

            return View(phone);
        }

        [HttpPost]
        public IActionResult Display(Phone phone)
        {
            return Content($"{phone.Name} - {phone.Price}");
        }
    }
}

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Views/HtmlHelpers/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "HtmlHelpers", FormMethod.Post))
{
    @*<p>
            <label>Модель</label><br />
            <input type="text" name="Name" />
        </p>
        <p>
            <label>Цена</label><br />
            <input type="number" name="Price" />
        </p>
        <p>
            <input type="submit" value="Отправить" />
        </p>*@

    <p>
        <label>Модель</label><br />
        @Html.TextBox("Name")
    </p>
    <p>
        <label>Цена</label><br />
        @Html.TextBox("Price", "", new { type = "number" })
    </p>
    <p>
        <input type="submit" value="Отправить" />
    </p>

}

@Html.Label("Name", "Модель")
<label for="Name">Модель</label>

@Html.TextArea("text", "привет мир")
<textarea cols="20" id="text" name="text" rows="2">привет мир
</textarea>


@Html.TextArea("text", "привет мир", 5, 50, null)
<textarea cols="50" id="text" name="text" rows="5">привет мир</textarea>

@Html.Hidden("PhoneId", "2")
<input id="PhoneId" name="PhoneId" type="hidden" value="2" />

@Html.Password("UserPassword", "val")
<input id="UserPassword" name="UserPassword" type="password" value="val" />

@Html.RadioButton("color", "red")
<span>красный</span> <br />
@Html.RadioButton("color", "blue")
<span>синий</span> <br />
@Html.RadioButton("color", "green", true)
<span>зеленый</span>

<input id="color" name="color" type="radio" value="red" />
<span>красный</span> <br />
<input id="color" name="color" type="radio" value="blue" />
<span>синий</span> <br />
<input checked="checked" id="color" name="color" type="radio" value="green" />
<span>зеленый</span>

@Html.CheckBox("Enable", false)
<input id="Enable" name="Enable" type="checkbox" value="true">
<input name="Enable" type="hidden" value="false">

@Html.DropDownList("phone", new SelectList(new string[] { "iPhone 7 Pro", "Galaxy 7 Edge", "HTC 10", "Honor 5X" }), "Выберите модель")

<select id="phone" name="phone">
    <option value="">Выберите модель</option>
    <option>iPhone 7 Pro</option>
    <option>Galaxy 7 Edge</option>
    <option>HTC 10</option>
    <option>Honor 5X</option>
</select>

@Html.DropDownList("phoneid", ViewBag.Phones as SelectList)

@Html.ListBox("phones", new MultiSelectList(new string[] { "iPhone 7 Pro", "Galaxy 7 Edge", "HTC 10", "Honor 5X" }))

<select id="phones" multiple="multiple" name="phones">
    <option>iPhone 7 Pro</option>
    <option>Galaxy 7 Edge</option>
    <option>HTC 10</option>
    <option>Honor 5X</option>
</select>

@using (Html.BeginForm("Create", "HtmlHelpers", FormMethod.Post))
{
    @Html.DropDownList("daytime", Html.GetEnumSelectList(typeof(TimeOfDay)))
    <br />
    <p>
        <input type="submit" value="Отправить" />
    </p>
}

@model MetanitExampleCoreMVC.Models.Phone

@using (Html.BeginForm("Create", "HtmlHelpers", FormMethod.Post))
{
    <p>
        @Html.LabelFor(m => m.Name, "Модель")<br />
        @Html.TextBoxFor(m => m.Name)
    </p>
    <p>
        @Html.LabelFor(m => m.Price, "Цена")<br />
        @Html.TextBoxFor(m => m.Price, "", new { type = "number" })
    </p>
    <p>
        <input type="submit" value="Отправить" />
    </p>
}

<input data-val="true" data-val-required="The Price field is required." id="Price" name="Price" type="number" value="">

@Html.HiddenFor(m => m.Id)
<input id="Id" name="Id" type="hidden" value="[значение_m.Id]" />

@*@Html.CheckBoxFor(m => m.Enable, false)
    <input id="Enable" name="Enable" type="checkbox" value="true" />
    <input name="Enable" type="hidden" value="false">*@

@Html.LabelFor(m => m.Name, "Модель")
<label for="Name">Модель</label>

@*@Html.PasswordFor(m => m.Password)
<input id="Password" name="Password" type="password" />*@

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Views/HtmlHelpers/Display.cshtml
@model MetanitExampleCoreMVC.Models.Phone
@{
    ViewData["Title"] = "Display";
}

<h2>Display</h2>

<p>
    <b>Id:</b><br />
    @Html.Display("Id")
</p>
<p>
    <b>Модель:</b><br />
    @Html.Display("Name")
</p>
<p>
    <b>Цена:</b><br />
    @Html.Display("Price")
</p>


<p>
    <b>Id:</b><br />
    @Html.DisplayFor(m => m.Id)
</p>
<p>
    <b>Модель:</b><br />
    @Html.DisplayFor(m => m.Name)
</p>
<p>
    <b>Цена:</b><br />
    @Html.DisplayFor(m => m.Price)
</p>

@Html.DisplayForModel()

@using (Html.BeginForm("Display", "HtmlHelpers", FormMethod.Post))
{
    <p>
        @Html.LabelFor(m => m.Name, "Модель")<br />
        @Html.EditorFor(m => m.Name)
    </p>
    <p>
        @Html.LabelFor(m => m.Price, "Цена")<br />
        @Html.EditorFor(m => m.Price)
    </p>
    <p>
        <input type="submit" value="Отправить" />
    </p>
}


@Html.ActionLink("О сайте", "About")
<a href="/Home/About">О сайте</a>

@Html.ActionLink("Список книг", "List", "Book")

@Html.ActionLink("Достоевский", "Index", "Book", new { author = "Достоевский", id = 5 }, null)

@Html.ActionLink("Все книги", "Index", "Book", new { author = "Толстой", id = 10 }, new { id = "Tolstoi", @class = "link" })

<a class="link" href="/Book/Index/10?author=%D0%A2%D0%BE%D0%BB%D1%81%D1%82%D0%BE%D0%B9" id="Tolstoi">Все книги</a>

@Html.RouteLink("Все книги", new { controller = "Book", action = "Index", author = "Толстой", id = 10 }, new { id = "Tolstoi", @class = "link" })

@Html.RouteLink("Все книги", "Default", new { action = "Show" })

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Views/HtmlHelpers/Index.cshtml
<h2>Index</h2>

@{
    ViewData["Title"] = "Home Page";
}

@{
    string[] cities = new string[] { "Лондон", "Париж", "Берлин" };
    string[] countries = new string[] { "Великобритания", "Франция", "Германия" };
}

<h3>Города</h3>
@Html.CreateList(cities)
<br />
<h3>Страны</h3>
<!-- или можно вызвать так -->
@ListHelper.CreateList(Html, countries)