MetanitExampleCoreMVC/MetanitExampleCoreMVC/Models/PhoneRequired.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MetanitExampleCoreMVC.Models
{
    public class PhoneRequired
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Range(50, 500)]
        [Required]
        public int Price { get; set; }

        [Required]
        public int CompanyId { get; set; }
        public Company Company { get; set; }
    }
}

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Controllers/TagHelpersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MetanitExampleCoreMVC.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MetanitExampleCoreMVC.Controllers
{
    public class TagHelpersController : Controller
    {
        IEnumerable<Company> companies = new List<Company>()
        {
            new Company { Id = 1, Name = "Apple" },
            new Company { Id = 2, Name = "Samsung" },
            new Company { Id=3, Name="Microsoft" }
        };

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(DayTimeViewModel model)
        {
            return Content(model.Period.ToString());
        }

        public IActionResult Create()
        {
            ViewBag.Companies = new SelectList(companies, "Id", "Name");
            return View();
        }

        [HttpPost]
        public string Create(Phone phone)
        {
            Company company = companies.FirstOrDefault(c => c.Id == phone.CompanyId);
            return $"Добавлен новый элемент: {phone.Name} ({company?.Name})";
        }

        public IActionResult PhoneRequired()
        {
            ViewBag.Companies = new SelectList(companies, "Id", "Name");
            return View();
        }

        [HttpPost]
        public string PhoneRequired(PhoneRequired phoneRequired)
        {
            return $"{phoneRequired.Name}";
        }
    }
}

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Views/TagHelpers/Create.cshtml
@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

@model MetanitExampleCoreMVC.Models.Phone

<h2>Добавление телефона</h2>

<form asp-action="Create" asp-controller="TagHelpers" asp-antiforgery="true">
    <div>
        <div>
            <label asp-for="Name"></label>
            <input type="text" asp-for="Name" />
        </div>
        <div>
            <label asp-for="Price"></label>
            <input type="number" asp-for="Price" />
        </div>
        <div>
            <label asp-for="CompanyId"></label>
            <select asp-for="CompanyId" asp-items="ViewBag.Companies"></select>
        </div>
        <div>
            <input type="submit" value="Save" />
        </div>
    </div>
</form>

<label asp-for="Name"></label>
<input type="text" asp-for="Name" />
<span asp-validation-for="Name" />

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Views/TagHelpers/Index.cshtml
@model MetanitExampleCoreMVC.Models.DayTimeViewModel
@using MetanitExampleCoreMVC.TagHelpers
@{
    ViewData["Title"] = "Index";
    List<string> countries = new List<string> { "Бразилия", "Аргентина", "Уругвай" };
    List<string> cities = new List<string> { "Бразилиа", "Буэйнос-Айрес", "Монтевидео" };
}

<h2>Index</h2>

<a asp-controller="TagHelpers" asp-action="Index">Контакты</a>

<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
        asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
        asp-fallback-test="window.jQuery"
        crossorigin="anonymous"
        integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
</script>

<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/css/bootstrap.min.css"
      asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
      asp-fallback-test-class="hidden" asp-fallback-test-property="visibility" asp-fallback-test-value="hidden" />


<link asp-href-include="~/css/**/*.css" />

<form method="post">
    <div>
        <div>
            <label asp-for="Period">Время суток</label>
            <select asp-for="Period" asp-items="Html.GetEnumSelectList<DayTime>()"></select>
        </div>
        <div>
            <input type="submit" value="Save" />
        </div>
    </div>
</form>

<vk></vk>
<socials><vk></vk></socials>

<vk group="metanit">Metanit</vk> <br />
<vk group="habr">Хабрахабр</vk>

<vk group="metanit" condition="false">Metanit</vk>
<vk group="habr" condition="true">Хабрахабр</vk>

<vk info='new LinkInfo{Color="red", FontFamily="Verdana", FontSize=18}'>Група в вк</vk>

<vk>Ссылка на профиль</vk>

<div header divtitle>Первый параграф</div>
<div header divtitle>Второй параграф</div>
<article-header>Заголовок!</article-header>

<form-header>Заголовок1</form-header>
<form-header form-title>Заголовок2</form-header>

<form>
    <form-header form-title>Заголовок3</form-header>
</form>

<list elements="countries"></list>
<list elements="cities"></list>

@using MetanitExampleCoreMVC.ViewModels @*Пространство имен модели Book*@
@{
    BookViewModel mybook = new BookViewModel { Id = 1, Title = "Война и мир", Author = "Л. Толстой", Year = 1862 };
}

<book-info book="mybook"></book-info>

MetanitExampleCoreMVC/MetanitExampleCoreMVC/Views/TagHelpers/PhoneRequired.cshtml
@model MetanitExampleCoreMVC.Models.PhoneRequired
@{
    ViewData["Title"] = "PhoneRequired";
}

<h2>PhoneRequired</h2>

<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

<form asp-antiforgery="true" asp-action="PhoneRequired" asp-controller="TagHelpers">
    <div>
        <div class="validation" asp-validation-summary="All"></div>
        <div>

            <label asp-for="Name"></label><br />
            <input type="text" asp-for="Name" />
            <span asp-validation-for="Name"></span>
        </div>

        <div>
            <label asp-for="Price"></label><br />
            <input asp-for="Price" />
            <span asp-validation-for="Price"></span>
        </div>

        <div>
            <label asp-for="CompanyId"></label><br />
            <select asp-for="CompanyId" asp-items="ViewBag.Companies">
                <option selected="selected" disabled="disabled">Выберите компанию</option>
            </select>
            <span asp-validation-for="CompanyId"></span>
        </div>
        <div>
            <input type="submit" value="Save" />
        </div>
    </div>
</form>

<cache expires-after="@TimeSpan.FromMinutes(5)">
    @Html.Partial("BookInfo")
</cache>

<cache expires-on="@DateTime.Now.AddDays(1)">
    @Html.Partial("BookInfo")
</cache>

<cache expires-sliding="@TimeSpan.FromMinutes(10)">
    @Html.Partial("BookInfo")
</cache>

<cache expires-after="@TimeSpan.FromMinutes(15)" vary-by-user="true">

</cache>

<cache expires-after="@TimeSpan.FromMinutes(15)" vary-by-route="id">

</cache>

<cache vary-by-query="name">

</cache>

<cache vary-by-cookie="pubid">

</cache>

<cache vary-by-header="User-Agent">

</cache>

<cache vary-by="@ViewBag.Id">

</cache>  